title: Site
data:
  logo: aa_logo.png
  icon: favicon-32x32.png
  header: eb9380ab-8059-4e7c-bd6e-aae985e630d9
  insert_into_head:
    code: |-
      <style>
        header nav li:last-child a {
      	background: var(--primary-500);
      	color: white;
      	padding: .5rem 1rem;
      	border-radius: .25rem;
      	margin-left: 2rem;
        }
      </style>
    mode: htmlmixed
  insert_into_body:
    code: null
    mode: htmlmixed
