tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: logo
            field:
              max_files: 1
              mode: grid
              container: assets
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: Logo
              icon: assets
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
              width: 75
          -
            handle: icon
            field:
              max_files: 1
              mode: grid
              container: assets
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: Icon
              icon: assets
              width: 25
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
