tabs:
  general:
    display: General
    sections:
      -
        fields:
          -
            handle: logo
            field:
              max_files: 1
              mode: grid
              container: assets
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: Logo
              icon: assets
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
              width: 75
          -
            handle: icon
            field:
              max_files: 1
              mode: grid
              container: assets
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: Icon
              icon: assets
              width: 25
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          -
            handle: header
            field:
              max_items: 1
              mode: default
              create: true
              collections:
                - partials
              type: entries
              display: Header
              icon: entries
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          -
            handle: footer
            field:
              max_items: 1
              mode: default
              create: true
              collections:
                - partials
              type: entries
              display: Footer
              icon: entries
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
  advanced:
    display: Advanced
    sections:
      -
        fields:
          -
            handle: insert_into_head
            field:
              theme: material
              mode: htmlmixed
              mode_selectable: true
              indent_type: tabs
              indent_size: 4
              key_map: default
              line_numbers: true
              line_wrapping: true
              antlers: true
              type: code
              display: '<head>'
              icon: code
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
              instructions: 'Any code placed here will be injected into the &lt;head&gt; tag.'
          -
            handle: insert_into_body
            field:
              theme: material
              mode: htmlmixed
              mode_selectable: true
              indent_type: tabs
              indent_size: 4
              key_map: default
              line_numbers: true
              line_wrapping: true
              antlers: false
              type: code
              display: '<body>'
              icon: code
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
              instructions: 'Any code placed here will be injected into the &lt;body&gt; tag.'
