title: Services
template: templates/service
layout: layout
revisions: true
route: "services/{{ parent_uri | replace('services/', '') | replace('.html', '') }}/{{ slug }}"
sort_dir: asc
default_status: draft
date_behavior:
  past: public
  future: private
preview_targets:
  -
    label: Entry
    url: '{permalink}'
    refresh: true
structure:
  root: false
  slugs: true
