title: Services
template: default
layout: layout
revisions: true
route: "services/{{ parent_uri | replace('services/', '') | replace('.html', '') }}/{{ slug }}.html"
sort_dir: asc
date_behavior:
  past: public
  future: private
preview_targets:
  -
    label: Entry
    url: '{permalink}'
    refresh: true
structure:
  root: false
  slugs: true
