tabs:
  content:
    display: Content
    sections:
      -
        display: 'Service Content'
        fields:
          -
            handle: hero
            field:
              type: tab
              display: Hero
              icon: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256"><path fill="currentColor" d="M253.75 166.28L231.46 92a13.91 13.91 0 0 0-13.41-10H208a6 6 0 0 0 0 12h10.05a2 2 0 0 1 1.95 1.42L240 162h-35.54l-21-70a13.91 13.91 0 0 0-13.41-10H160a6 6 0 0 0 0 12h10.05a2 2 0 0 1 1.95 1.42L192 162h-35.54l-21-70a13.91 13.91 0 0 0-13.41-10H38a13.91 13.91 0 0 0-13.46 10L2.28 166.2v.2a2.79 2.79 0 0 0-.1.39a.11.11 0 0 0 0 .05A6 6 0 0 0 8 174h240a6 6 0 0 0 5.75-7.72ZM36 95.42A2 2 0 0 1 38 94h84.1a2 2 0 0 1 1.9 1.43L144 162H16.06Z"></path></svg>'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            import: title
            prefix: hero_
          -
            import: content
            prefix: hero_
          -
            handle: main_content
            field:
              type: tab
              display: 'Main Content'
              icon: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256"><path fill="currentColor" d="M253.75 166.28L231.46 92a13.91 13.91 0 0 0-13.41-10H208a6 6 0 0 0 0 12h10.05a2 2 0 0 1 1.95 1.42L240 162h-35.54l-21-70a13.91 13.91 0 0 0-13.41-10H160a6 6 0 0 0 0 12h10.05a2 2 0 0 1 1.95 1.42L192 162h-35.54l-21-70a13.91 13.91 0 0 0-13.41-10H38a13.91 13.91 0 0 0-13.46 10L2.28 166.2v.2a2.79 2.79 0 0 0-.1.39a.11.11 0 0 0 0 .05A6 6 0 0 0 8 174h240a6 6 0 0 0 5.75-7.72ZM36 95.42A2 2 0 0 1 38 94h84.1a2 2 0 0 1 1.9 1.43L144 162H16.06Z"></path></svg>'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            import: content
  staff_locations:
    display: 'Staff & Locations'
    sections:
      -
        display: 'Staff & Locations'
        instructions: 'Attach staff member and location entries to this service. This is a two-way relation, staff and location entries will stay synced.'
        fields:
          -
            handle: staff
            field:
              mode: default
              create: true
              collections:
                - staff
              type: entries
              display: Staff
              icon: entries
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
              width: 50
              replicator_preview: true
              always_save: true
              unless:
                override_staff: 'equals true'
          -
            handle: locations
            field:
              mode: default
              create: true
              collections:
                - locations
              type: entries
              display: Locations
              icon: entries
              width: 50
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
              replicator_preview: true
              always_save: true
              unless:
                override_staff: 'equals true'
          -
            handle: staff_is_customized
            field:
              html: 'This service has custom staff sections. Existing relations are unaffected.'
              type: html
              display: 'Staff Is Customized'
              icon: html
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: true
              if:
                override_staff: 'equals true'
      -
        display: 'Custom Staff'
        fields:
          -
            handle: override_staff
            field:
              default: false
              type: toggle
              display: 'Override Staff'
              icon: toggle
              instructions: 'Customize the staff section of this service. Does not affect existing relations.'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: staff_sections
            field:
              collapse: false
              previews: true
              fullscreen: true
              sets:
                new_set_group:
                  display: 'New Set Group'
                  instructions: null
                  icon: null
                  sets:
                    staff_section:
                      display: 'Staff Section'
                      instructions: null
                      icon: null
                      fields:
                        -
                          handle: text_field
                          field:
                            input_type: text
                            antlers: false
                            type: text
                            display: 'Section Title'
                            icon: text
                            listable: hidden
                            instructions_position: above
                            visibility: visible
                            replicator_preview: true
                            hide_display: false
                            placeholder: 'Cancer Care Provider'
                        -
                          handle: section_staff_members
                          field:
                            mode: default
                            create: true
                            collections:
                              - staff
                            type: entries
                            display: 'Section Staff Members'
                            icon: entries
                            listable: hidden
                            instructions_position: above
                            visibility: visible
                            replicator_preview: true
                            hide_display: false
              type: replicator
              display: 'Staff Sections'
              icon: replicator
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              always_save: true
              if:
                override_staff: 'equals true'
  details:
    display: Details
    sections:
      -
        display: 'Service Details'
        fields:
          -
            handle: eloqua_form
            field:
              type: tab
              display: 'Eloqua Form'
              icon: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256"><path fill="currentColor" d="M253.75 166.28L231.46 92a13.91 13.91 0 0 0-13.41-10H208a6 6 0 0 0 0 12h10.05a2 2 0 0 1 1.95 1.42L240 162h-35.54l-21-70a13.91 13.91 0 0 0-13.41-10H160a6 6 0 0 0 0 12h10.05a2 2 0 0 1 1.95 1.42L192 162h-35.54l-21-70a13.91 13.91 0 0 0-13.41-10H38a13.91 13.91 0 0 0-13.46 10L2.28 166.2v.2a2.79 2.79 0 0 0-.1.39a.11.11 0 0 0 0 .05A6 6 0 0 0 8 174h240a6 6 0 0 0 5.75-7.72ZM36 95.42A2 2 0 0 1 38 94h84.1a2 2 0 0 1 1.9 1.43L144 162H16.06Z"></path></svg>'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: eloqua_form_embed_code
            field:
              theme: material
              mode: htmlmixed
              mode_selectable: false
              indent_type: tabs
              indent_size: 4
              key_map: default
              line_numbers: true
              line_wrapping: true
              antlers: false
              type: code
              display: 'Eloqua Form Embed Code'
              icon: code
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: child_services
            field:
              type: tab
              display: 'Child Services'
              icon: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256"><path fill="currentColor" d="M253.75 166.28L231.46 92a13.91 13.91 0 0 0-13.41-10H208a6 6 0 0 0 0 12h10.05a2 2 0 0 1 1.95 1.42L240 162h-35.54l-21-70a13.91 13.91 0 0 0-13.41-10H160a6 6 0 0 0 0 12h10.05a2 2 0 0 1 1.95 1.42L192 162h-35.54l-21-70a13.91 13.91 0 0 0-13.41-10H38a13.91 13.91 0 0 0-13.46 10L2.28 166.2v.2a2.79 2.79 0 0 0-.1.39a.11.11 0 0 0 0 .05A6 6 0 0 0 8 174h240a6 6 0 0 0 5.75-7.72ZM36 95.42A2 2 0 0 1 38 94h84.1a2 2 0 0 1 1.9 1.43L144 162H16.06Z"></path></svg>'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: show_child_services
            field:
              default: false
              type: toggle
              display: 'Show Child Services'
              icon: toggle
              instructions: "By enabling this option, this service will display it's `children` services. To feature child services, set this as the `parent` page."
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: child_services_title
            field:
              input_type: text
              antlers: false
              type: text
              display: 'Child Services Title'
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              if:
                show_child_services: 'equals true'
              always_save: true
          -
            handle: child_services_text
            field:
              buttons:
                - bold
                - italic
                - removeformat
                - anchor
              smart_typography: true
              save_html: false
              inline: false
              toolbar_mode: fixed
              reading_time: false
              word_count: false
              fullscreen: true
              allow_source: true
              enable_input_rules: true
              enable_paste_rules: true
              remove_empty_nodes: false
              antlers: false
              link_noopener: false
              link_noreferrer: false
              target_blank: false
              always_show_set_button: false
              collapse: false
              previews: true
              type: bard
              display: 'Child Services Text'
              icon: bard
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              always_save: true
              if:
                show_child_services: 'equals true'
          -
            handle: external_link
            field:
              type: tab
              display: 'External Link'
              icon: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256"><path fill="currentColor" d="M253.75 166.28L231.46 92a13.91 13.91 0 0 0-13.41-10H208a6 6 0 0 0 0 12h10.05a2 2 0 0 1 1.95 1.42L240 162h-35.54l-21-70a13.91 13.91 0 0 0-13.41-10H160a6 6 0 0 0 0 12h10.05a2 2 0 0 1 1.95 1.42L192 162h-35.54l-21-70a13.91 13.91 0 0 0-13.41-10H38a13.91 13.91 0 0 0-13.46 10L2.28 166.2v.2a2.79 2.79 0 0 0-.1.39a.11.11 0 0 0 0 .05A6 6 0 0 0 8 174h240a6 6 0 0 0 5.75-7.72ZM36 95.42A2 2 0 0 1 38 94h84.1a2 2 0 0 1 1.9 1.43L144 162H16.06Z"></path></svg>'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: link_externally
            field:
              default: false
              type: toggle
              display: 'Link Externally'
              icon: toggle
              instructions: 'This service should link to an external URL'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: external_url
            field:
              input_type: text
              placeholder: 'https://www.google.com/'
              antlers: true
              type: text
              display: 'External URL'
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              if:
                link_externally: 'equals true'
              always_save: true
          -
            handle: search_terms
            field:
              type: tab
              display: 'Search Terms'
              icon: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256"><path fill="currentColor" d="M253.75 166.28L231.46 92a13.91 13.91 0 0 0-13.41-10H208a6 6 0 0 0 0 12h10.05a2 2 0 0 1 1.95 1.42L240 162h-35.54l-21-70a13.91 13.91 0 0 0-13.41-10H160a6 6 0 0 0 0 12h10.05a2 2 0 0 1 1.95 1.42L192 162h-35.54l-21-70a13.91 13.91 0 0 0-13.41-10H38a13.91 13.91 0 0 0-13.46 10L2.28 166.2v.2a2.79 2.79 0 0 0-.1.39a.11.11 0 0 0 0 .05A6 6 0 0 0 8 174h240a6 6 0 0 0 5.75-7.72ZM36 95.42A2 2 0 0 1 38 94h84.1a2 2 0 0 1 1.9 1.43L144 162H16.06Z"></path></svg>'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            import: searchterms
  seo:
    display: SEO
    sections:
      -
        display: 'Search Engine Optimization'
        fields:
          -
            import: seo
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
              instructions_position: above
              listable: hidden
              visibility: visible
              replicator_preview: true
              input_type: text
              antlers: false
              hide_display: false
              display: 'Service Title'
          -
            handle: slug
            field:
              type: slug
              localizable: true
          -
            import: image
          -
            handle: parent
            field:
              type: entries
              collections:
                - services
              max_items: 1
              listable: false
              localizable: true
title: Service
